# TX00DQ05-3001 Reinforcement Learning, exercises 1

In [1]:
# import numpy and other useful packages
import numpy as np
import numpy.linalg as LA

## Weather example

P is the transition matrix and t0 weather on day 0

In [2]:
P = np.array(([0.2, 0.8], [0.6, 0.4]))
t0 = np.array([0.0, 1.0])

t1 = np.dot(t0, P)
print(t1)
t2 = np.dot(t1, P)
print(t2)
print(np.dot(t0, LA.matrix_power(P, 2)))
print(np.dot(t0, LA.matrix_power(P, 10)))
print(np.dot(t0, LA.matrix_power(P, 30)))
print(np.dot(t0, LA.matrix_power(P, 50)))

[0.6 0.4]
[0.36 0.64]
[0.36 0.64]
[0.42852649 0.57147351]
[0.42857143 0.57142857]
[0.42857143 0.57142857]


## Exercise 1

Check some matrix algebra identities with numpy.

* A + B = B + A
* cA + cB = c(A + B) where c is scalar
* if shape of A is (x,y), shape of A.T (transpose) is (y,x) 
* if v is vector of shape (x,), then v dot A has shape (y,)
* verify that shape of A.T dot B is (y, y) and shape of A dot B.T is (x, x)

In [3]:
A = np.array(([1, 2, 3], [2, 0 ,2], [3, 0, 1], [4, 1 ,0]))
B = np.array(([0, 1, 2], [2, 1, 1], [2, 1, 0], [1, 2, 3]))

# YOUR CODE HERE

print('Identity 1: A + B = B + A')
print('A + B')
check1 = A + B
print(check1)
print('B + A')
check2 = B + A
print(check2)
print('check if A + B = B + A')
print(check1 == check2)

Identity 1: A + B = B + A
A + B
[[1 3 5]
 [4 1 3]
 [5 1 1]
 [5 3 3]]
B + A
[[1 3 5]
 [4 1 3]
 [5 1 1]
 [5 3 3]]
check if A + B = B + A
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
print('Identity 2: cA + cB = c(A + B) where c is scalar')
print('let c = 2')
c = 2
cA = c * A
cB = c * B
cAB = c * (A + B)
print('cA')
print(cA)
print('cB')
print(cB)
print('c(A + B)')
print(cAB)
print('cA + cB')
print(cA + cB)
print('check if cA + cB = c(A + B)')
print((cA + cB) == cAB)

Identity 2: cA + cB = c(A + B) where c is scalar
let c = 2
cA
[[2 4 6]
 [4 0 4]
 [6 0 2]
 [8 2 0]]
cB
[[0 2 4]
 [4 2 2]
 [4 2 0]
 [2 4 6]]
c(A + B)
[[ 2  6 10]
 [ 8  2  6]
 [10  2  2]
 [10  6  6]]
cA + cB
[[ 2  6 10]
 [ 8  2  6]
 [10  2  2]
 [10  6  6]]
check if cA + cB = c(A + B)
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
print('Identity 3: if shape of A is (x,y), shape of A.T (transpose) is (y,x)')
print('shape of A is ',end='')
print(A.shape)
print(A)
print('shape of A.T is ',end='')
print(A.transpose().shape)
print(A.transpose())

Identity 3: if shape of A is (x,y), shape of A.T (transpose) is (y,x)
shape of A is (4, 3)
[[1 2 3]
 [2 0 2]
 [3 0 1]
 [4 1 0]]
shape of A.T is (3, 4)
[[1 2 3 4]
 [2 0 0 1]
 [3 2 1 0]]


In [6]:
print('Identity 4: if v is vector of shape (x,), then v dot A has shape (y,)')
print('Shape of A is (x,y) = ',end="")
print(A.shape)
print('v is a vector of shape (x,) where x=4, let v = [2, 3, 4, 5]')
v = np.array(([2,3,4,5]))
print('Shape of v is ',end="")
print(v.shape)
print(v)
print('Shape of v dot A is ',end="")
vA = np.dot(v,A)
print(vA.shape)
print(vA)

Identity 4: if v is vector of shape (x,), then v dot A has shape (y,)
Shape of A is (x,y) = (4, 3)
v is a vector of shape (x,) where x=4, let v = [2, 3, 4, 5]
Shape of v is (4,)
[2 3 4 5]
Shape of v dot A is (3,)
[40  9 16]


In [7]:
print('Identity 5: verify that shape of A.T dot B is (y, y) and shape of A dot B.T is (x, x)')
shape1 = np.dot(A.transpose(),B)
shape2 = np.dot(A,B.transpose())
print('Shape of A.T dot B is ',end='')
print(shape1.shape)
print(shape1)
print('Shape of A dot B.T is ',end='')
print(shape2.shape)
print(shape2)

Identity 5: verify that shape of A.T dot B is (y, y) and shape of A dot B.T is (x, x)
Shape of A.T dot B is (3, 3)
[[14 14 16]
 [ 1  4  7]
 [ 6  6  8]]
Shape of A dot B.T is (4, 4)
[[ 8  7  4 14]
 [ 4  6  4  8]
 [ 2  7  6  6]
 [ 1  9  9  6]]


## Exercise 2

Throw a dice (1..6) repeadetly and maintain the mean value of the 
numbers continously (and without explicitly storing the numbers or their sum) by
computing a correction factor to the previous mean.

Hint: mean(n) = sum(n) / n = (sum(n-1) + a(n)) / n = (mean(n-1) * (n-1) + a(n)) / n =
mean(n-1) + (a(n) - mean(n-1)) / n

Stop computation when correction factor stays below eps for b rounds or if you reach maxiter iterations.

How does changing eps and b influence the number of iterations needed?

In [8]:
eps = 0.00001
b = 50
maxiter = 1000000

# YOUR CODE HERE

def roll_dice():
    return np.random.randint(1,7)

count = 0
n = int(input("Input your iterations: "))
if n > maxiter:
    print('Your number is greater than the maximum  iteration (1000000).')
    print('The iteration number is changed to maximum iteration (1000000).')
    n = maxiter
    
for i in range(n):
    number = roll_dice()
    print('Iter ' + str(i) +' number = ' + str(number))
    if i == 0:
        mean = number
    else:
        if (number - mean)/(i+1) <= eps:
            count += 1
        else:
            count = 0
        if count >= b:
            break
        mean = mean + (number - mean)/(i+1)

print('Final mean is ', mean)

Input your iterations: 10
Iter 0 number = 1
Iter 1 number = 4
Iter 2 number = 4
Iter 3 number = 6
Iter 4 number = 5
Iter 5 number = 1
Iter 6 number = 3
Iter 7 number = 3
Iter 8 number = 4
Iter 9 number = 6
Final mean is  3.7


## Exercise 3

Given transition matrix P and initial state t0 write 
an iterative algorithm to find the steady state.

Stopping condition is that the norm (length of vector, use LA.norm) 
does not change more than eps in an iteration

In [9]:
maxiter = 10000
eps = 0.0000001

P = np.array(([0.2, 0.1, 0.7], [1.0, 0.0, 0.0], [0.2, 0.2, 0.6]))
t0 = np.array([1.0, 0.0, 0.0])

# YOUR CODE HERE
for i in range(maxiter):
    print('Iter: ' + str(i) + ' state = ', end="")
    print(t0)
    prev_norm = LA.norm(t0)
    t0 = np.dot(t0,P)
    norm_diff = np.absolute(LA.norm(t0) - prev_norm)
    print('Norm difference is ' + str(norm_diff))
    print('--------------------------------------------')
    if norm_diff <= eps:
        break
        
print('Final state is ', end='')
print(t0, end='')
print(' with norm ',end='')
print(LA.norm(t0))
print('Number of iterations: ' + str(i+1))

Iter: 0 state = [1. 0. 0.]
Norm difference is 0.26515307716504666
--------------------------------------------
Iter: 1 state = [0.2 0.1 0.7]
Norm difference is 0.08862714597881283
--------------------------------------------
Iter: 2 state = [0.28 0.16 0.56]
Norm difference is 0.005744952994968022
--------------------------------------------
Iter: 3 state = [0.328 0.14  0.532]
Norm difference is 0.005978639274419328
--------------------------------------------
Iter: 4 state = [0.312  0.1392 0.5488]
Norm difference is 0.0008776321133950882
--------------------------------------------
Iter: 5 state = [0.31136 0.14096 0.54768]
Norm difference is 0.00033148427594276164
--------------------------------------------
Iter: 6 state = [0.312768 0.140672 0.54656 ]
Norm difference is 0.0001359260202444812
--------------------------------------------
Iter: 7 state = [0.3125376 0.1405888 0.5468736]
Norm difference is 8.06676956455199e-07
--------------------------------------------
Iter: 8 state = [0